### ISSUE TITLE
Word Search Game

### ISSUE THREAD

**Issue by akash435** [aliya-rahmani/Hacktoberfest-Projects#553]
In this script, will create a Word Search Game,
In this game there will be no. of levels and for each level there will be given a board in form of matrix, in which each cell will have an English alphabet and a word will be given.

for each level the player need to select either YES (means word is present in that board) or NO (if not present),

Also in board, the word can be in ant order, like horizontally, vertically, or in any diagonal
That word can be present in reverse order also.

**Comment by akash435** [comment]
@aliya-rahmani can i work on this issue under hacktoberfest?

**Comment by aliya-rahmani** [comment]
@akash435  Sure, I've assigned you this issue
